[package]
name = "kkv1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.5.3"
dashmap = "5.3.3"
rand = "0.8.5"